### ISSUE TITLE
Proposition: variable declaration of arrow functions should not require a typedef

### ISSUE THREAD

**Issue by na-ji** [yelloan/yelloan-tslint#11]
Hello,

I have a problem I encountered a few times, so I suggest an update of the rules.
The problem I encounter is with the rule [typedef](https://palantir.github.io/tslint/rules/typedef/) and more precisely the subrule `variable-declaration`. 
For me we should add the rule `variable-declaration-ignore-function` since the rules `arrow-call-signature` and `call-signature` already enforce the type definition of the functions.

With the `variable-declaration` only, we often have typings like this:
```typescript
const getApplication: (applicationId: string) => Promise<IApplication> = async (applicationId: string): Promise<IApplication> => {};
```

As you can see, the function signature is typed __twice__. This double typings is an overhead and can induce an error when refactoring. For instance I often rename the variable declaration typedef and forget to update the function typedef.

While with the `variable-declaration` and `variable-declaration-ignore-function`, it would look like this:
```typescript
const getApplication = async (applicationId: string): Promise<IApplication> => {};
```

What do you think?

Thanks!

**Comment by na-ji** [comment]
ping @yelloan/backend

**Comment by ccoeurderoy** [comment]
Makes sense! Thanks for your detailed explanation. Do not hesitate to open a Pull Request 😉

**Comment by pierreneveu** [comment]
This thing also bothers me ! nice :D
